### ISSUE TITLE
Error when install plugin using CLI

### ISSUE THREAD

**Issue by douglaszuqueto** [tago-io/tagocore#37]
Hi guys!

I have an error when install plugin using CLI.

```bash
➜  tagocore-v0.7.0-linux-x64 ./tagocore plugin-install 6930d8689d56a234319ad6a05d7fc4e7
[TagoCore CLI] ✖ 6930d8689d56a234319ad6a05d7fc4e7 - BE.decryptPluginConfigPassword is not a function
```

![Screenshot](https://user-images.githubusercontent.com/7410247/196246507-e3d5833f-a1b1-4b22-8390-116a8c049240.png)

**Comment by RicardoStoklosa** [comment]
Hi @douglaszuqueto, thanks for the report!
This bug will be addressed in next patch

**Comment by felipefdl** [comment]
Hi @douglaszuqueto, if you have some time, we are developing TagoCore v1.0
You can read more here: https://github.com/tago-io/tagocore/discussions/59

If you can help us test it, it will be great!

Thank you!

**Comment by douglaszuqueto** [comment]
@felipefdl Good news, my dear! I was very happy with the project's return.

I'm already following the development. Count on me!
